### ISSUE TITLE
Sabi.sys

### ISSUE THREAD

**Issue by dejanberic** [akastormseeker/samsung-hotkeys#1]
First of all, let me say this.
I can't thank you enough for your effort. Great work!

Now, I have just one small comment regarding using your app.
For me it worked with only having Sabi3.dll. I could not find Sabi.sys anywhere on my hard drive.

I have checked only backlight keyboard functionality, as it was my main concern, and it worked.
I do not know if some other actions require Sabi.sys.

I have a Samsung NP700Z5C-S01UB model.

**Comment by akastormseeker** [comment]
If you installed EasySettings to get the Sabi3.dll file, then it
automatically installed SABI.sys in the correct location and registered it
for you, like it's supposed to. In that case, all you need is the DLL for
my app to work. If you extracted the data.cab files, or if you copied the
files from a Windows 7 install, then you would have to move the .sys file
to the correct location and register it with the .reg file (and reboot
afterwards).

Regardless, if the keyboard backlight is working, then the .sys file is correctly installed.

On Mon, Feb 8, 2016 at 2:00 PM, dejanberic notifications@github.com wrote:

> First of all, let me say this.
> I can't thank you enough for your effort. Great work!
> 
> Now, I have just one small comment regarding using your app.
> For me it worked with only having Sabi3.dll. I could not find Sabi.sys
> anywhere on my hard drive.
> 
> I have checked only backlight keyboard functionality, as it was my main
> concern, and it worked.
> I do not know if some other actions require Sabi.sys.
> 
> I have a Samsung NP700Z5C-S01UB model.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/akastormseeker/samsung-hotkeys/issues/1.

## 

-- Tim J
